Repository androidvitb/Spendwise, pull requests merged in 2025-01, with the labels that each got.

#3 updating the scroll button to the homepage
  index.html
  input.css
  script.js
Labels: acwoc, easy

#5 added dark mode button
  index.html
  input.css
  script.js
Labels: acwoc, medium

#8 Fix dark mode toggle and update graph button functionality
  index.html
  input.css
  script.js
Labels: acwoc, easy

#11 Added Edit Expense Button
  index.html
  script.js
Labels: acwoc, medium

#15 Addition Currency Scroller, dynamically currency update, PDF and EXCEL export button option #14 (issue no.14)
  index.html
  script.js
Labels: acwoc, medium

#18 Project Updates: Add Expense Tagging and AI-Powered Insights Enhancing Features and User Experience #17 (Issue no. 17)
  README.md
  index.html
  input.css
  script.js
Labels: acwoc, medium

#21 Fixed both the issues of currency value dynamically update in AI summary and language translation of AI-summary#20 (Issue no. 20)
  index.html
  script.js
Labels: acwoc, medium

#22 Implmented Feedback Forum and Data Submission using Firebase
  .env.example
  .gitignore
  Firebase_Setup.md
  feedback.js
  index.html
  input.css
  script.js
  tailwind.config.js
Labels: acwoc, hard

#24 Added Receipt Scanning with OCR feature
  index.html
  input.css
  script.js
Labels: acwoc, hard

#23 Fixed Buttons
  about.html
  index.html
Labels: acwoc, easy

#26 added logo
  Images/SpendWise.png
  Images/SpendWise2.png
  about.html
  index.html
Labels: acwoc, medium

#28 feat: add rewards page with gamified money management features
  index.html
  input.css
  package-lock.json
  reward.html
Labels: acwoc, hard

#34 Added a Finance Game Feature to Improve User Engagement
  index.html
  input.css
  package-lock.json
  package.json
  script.js
Labels: acwoc, hard

#35 Added Budgeting Feature
  index.html
  script.js
Labels: acwoc, hard

#37 updated the footer
  index.html
  input.css
Labels: acwoc, easy

#41 removed an extra contact us option
  index.html
Labels: acwoc, easy

#46 🎉 Enhanced "Choose File" Button for a Better Look
  index.html
Labels: acwoc, easy

#48 Update index.html
  index.html
Labels: acwoc, easy

#53 Added Smooth Scrolling
  script.js
Labels: acwoc, easy

#54 Update reward.html
  reward.html
Labels: acwoc, medium

#55 Update index.html
  index.html
Labels: acwoc, easy

#57 [MAJOR PR] UI Design and Major Platform Workflow Enhancements
  .env.example
  .gitignore
  dashboard.css
  dashboard.html
  dashboard.js
  feedback.js
  index.html
  input.css
  package-lock.json
  script.js
Labels: acwoc, hard

#58 Fixed the Routing and Scripts Issue of the New UI Design & Updated Re…
  README.md
  index.html
  script.js
Labels: acwoc, hard

#60 Fixed the Deployment and Routing Issues of an Application
  .gitignore
  README.md
  index.html
  public/Firebase_Setup.md
  public/Images/SpendWise.png
  public/Images/SpendWise2.png
  public/Images/main-bg.png
  public/about.html
  public/dashboard.css
  public/dashboard.html
  public/dashboard.js
  public/index.html
  public/input.css
  public/reward.html
  public/script.js
  vercel.json
  vite.config.js
Labels: acwoc, hard

#66 ✨ Added Scroll Button to Homepage 🚀
  public/index.html
  public/input.css
Labels: acwoc, medium

#67 🛠️Fixed: Favicon Updated
  index.html
  public/index.html
Labels: acwoc, easy
